// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1j2Xc0ugZPRnRul-6g8XO8E8g6MIl3rg',
    appId: '1:440838970380:web:bcb734a43e0f9e26da6229',
    messagingSenderId: '440838970380',
    projectId: 'ameko-pro',
    authDomain: 'ameko-pro.firebaseapp.com',
    storageBucket: 'ameko-pro.appspot.com',
    measurementId: 'G-GNDPYJMLQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD786fJkcf3pOVZWR3Otw4Dl5zvLn4gl5Y',
    appId: '1:440838970380:android:aa455597c7aea13dda6229',
    messagingSenderId: '440838970380',
    projectId: 'ameko-pro',
    storageBucket: 'ameko-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfpaIkUoYIrH4_JfIbWdMPPOOEG1xk8PQ',
    appId: '1:440838970380:ios:3dc6c58fe403ad44da6229',
    messagingSenderId: '440838970380',
    projectId: 'ameko-pro',
    storageBucket: 'ameko-pro.appspot.com',
    iosBundleId: 'com.shalmon.amekopro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfpaIkUoYIrH4_JfIbWdMPPOOEG1xk8PQ',
    appId: '1:440838970380:ios:3dc6c58fe403ad44da6229',
    messagingSenderId: '440838970380',
    projectId: 'ameko-pro',
    storageBucket: 'ameko-pro.appspot.com',
    iosBundleId: 'com.shalmon.amekopro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1j2Xc0ugZPRnRul-6g8XO8E8g6MIl3rg',
    appId: '1:440838970380:web:3aef5d0978232ec4da6229',
    messagingSenderId: '440838970380',
    projectId: 'ameko-pro',
    authDomain: 'ameko-pro.firebaseapp.com',
    storageBucket: 'ameko-pro.appspot.com',
    measurementId: 'G-ZLK46G3Q06',
  );
}
